# Допустимые исполнители:
# [CONSOLE] - выполнить действие от имени консоли
# [PLAYER] - выполнить действие от имени игрока (Не нужно писать /)
# [TITLE] - Вывести сообщение игроку на экран (Написанное после ; будет отображено в сабтитле)
# [ACTIONBAR] - Вывести сообщение игроку над хотбаром (В екшбаре)
# [MESSAGE] - Отобразить сообщение игроку в чате
# [PLAY_SOUND] - Проиграть музыку игроку (Указывать ЗВУК;ГРОМКОСТЬ;НАПРАВЛЕНИЕ (Громкость и направление необязательно))
#
# Доступные плейсхолдеры:
# %player% - Ник игрока
# %world% - Мир в котором игрок упал в пустоту
#
# Настройки миров (Можно оставить пустым и тогда будет выключено)
worlds:
  # Название мира (Можно добавить сколько угодно миров)
  Spawn:
    # Высота на которой к игроку применится команда
    execute-on-height: 0
    # Нужно указать время в секундах для того, чтобы одни и те же команды не применялись к игроку несколько раз.
    # (Фикс ошибки которая есть в многих подобных плагинах)
    repeat-fix: 3
    # Выполняемые команды
    execute-commands:
    - '[CONSOLE] rtp %player%'
    - '[TITLE] &6РТП;&aУспех!'
    - '[MESSAGE] &fВы были телепортированы в обычный мир, чтобы начать выживать'
  # Пример
  world:
    execute-on-height: 0
    repeat-fix: 3
    execute-commands:
    - '[PLAY_SOUND] BLOCK_NOTE_BELL;3'
    - '[PLAYER] spawn'
    - '[TITLE] &aСпасенье;&fТы был спасён от смерти!'

# Сообщения
messages:
  # Сообщение при перезагрузке плагина
  reload-message: '&aПлагин VoidFall успешно перезагружен.'
  # Сообщения если не хватает прав на использование команды
  no-permission: '&cИзвини, но у тебя не хватает прав на использование данной команды.'

# Нужно если у вас вдруг перестанут работать к примеру звуки или отображаться сообщения.
debug-mode: false