# Допустимые исполнители:
# [CONSOLE] - выполнить действие от имени консоли
# [PLAYER] - выполнить действие от имени игрока (Не нужно писать /)
# [TITLE] - Вывести сообщение игроку на экран (Написанное после ; будет отображено в сабтитле)
# [ACTIONBAR] - Вывести сообщение игроку над хотбаром (В екшбаре)
# [MESSAGE] - Отобразить сообщение игроку в чате
# [PLAY_SOUND] - Проиграть музыку игроку (Указывать ЗВУК;ГРОМКОСТЬ;НАПРАВЛЕНИЕ (Громкость и направление необязательно))
#
# Доступные плейсхолдеры:
# %player% - Ник игрока
# %world% - Мир в котором игрок упал в пустоту
#
# Настройки миров (Можно оставить пустым и тогда будет выключено)
worlds:
  # Новое
  world:
    floor:
      executing-height: 0
      repeat-fix: 3
      random: false
      execute-commands:
        - '[PLAY_SOUND] BLOCK_NOTE_BELL;3'
        - '[PLAYER] spawn'
        - '[TITLE] &aСпасенье;&fТы был спасён от смерти!'
#    roof:
#      executing-height: 127
#      repeat-fix: 3
#      random: false
#      execute-commands:
#        - '[PLAY_SOUND] BLOCK_NOTE_BELL;3'
#        - '[PLAYER] spawn'
#        - '[TITLE] &aСпасенье;&fТы был спасён от смерти!'

# Сообщения
messages:
  # Сообщение при перезагрузке плагина
  reload-message: '&aПлагин VoidFall успешно перезагружен.'
  # Сообщения если не хватает прав на использование команды
  no-permission: '&cИзвини, но у тебя не хватает прав на использование данной команды.'

# Нужно если у вас вдруг перестанут работать к примеру звуки или отображаться сообщения.
debug-mode: false
config-version: 1.1
check-updates: false