name: VoidFall
description: Execute a command to a player who has fallen into the void
version: '${project.version}'

authors: [ noslowdwn ]

softdepend: [ PlaceholderAPI, WorldGuardEvents ]

main: noslowdwn.voidfall.VoidFall

commands:
  voidfall: {}

permissions:
  voidfall.reload:
    default: op
    description: Allows you to reload the plugin
  voidfall.updates:
    default: false
    description: Allows you to see updates notifications on join