name: '${name}'
description: '${description}'
version: '${project.version}'

main: com.github.groundbreakingmc.voidfall.VoidFall

author: '${author}'
website: '${url}'

softdepend: [ PlaceholderAPI, WorldGuardEvents ]

commands:
  voidfall: {}

permissions:
  voidfall.reload:
    default: op
    description: Allows you to reload the plugin