name: VoidFall
description: Execute an action for the player who triggered the event
version: '${project.version}'

author: Groundbreakingmc

softdepend: [ PlaceholderAPI, WorldGuardEvents ]

main: groundbreakingmc.voidfall.VoidFall

commands:
  voidfall: {}

permissions:
  voidfall.reload:
    default: op
    description: Allows you to reload the plugin