name: VoidFall
description: Execute an action for the player who triggered the event
version: '${project.version}'

authors: [ noslowdwn ]

softdepend: [ PlaceholderAPI, WorldGuardEvents ]

main: noslowdwn.voidfall.VoidFall

commands:
  voidfall: {}

permissions:
  voidfall.reload:
    default: op
    description: Allows you to reload the plugin